# This is a basic workflow to help you get started with Actions

name: NbodyGradient-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == '0.7' }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1','0.7']
        os: [ubuntu-latest, macOS-latest]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # from 'julia-runtest' GitHub action.
    - uses: julia-actions/setup-julia@v1
      with: 
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/julia-runtest@latest  
